spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    redis:
      host: ${REDIS_HOST}

  mail:
    host: smtp.gmail.com
    port: 587
    username: mshas18@freeuni.edu.ge
    password: angelozi0000
    properties:
      mail:
        smtp:
          starttls:
            enable: true


util:
  jwt:
    secret: cFy/DJh+eQW0dCLLWpygzauKN3EBWRDwLbpJUus0ffAvOyHay5+FQCEBlnq0Wqv5ZnC5IgW5xJe91+XSyLo/GkxYp8qRh0ayUZInsRbmhEOaGIydUh5QU8XPiOTU5wLIeK
    expiration: 1000